# Generated by Django 5.2.8 on 2025-11-17 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EjercicioContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(default='ABIERTO', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PlanCuentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre_cuenta', models.CharField(max_length=200)),
                ('tipo_cuenta', models.CharField(choices=[('A', 'Activo'), ('P', 'Pasivo'), ('C', 'Capital'), ('I', 'Ingreso'), ('G', 'Gasto')], max_length=1)),
                ('nivel', models.IntegerField()),
                ('cuenta_padre', models.CharField(blank=True, max_length=20, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AsientoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_asiento', models.IntegerField()),
                ('fecha', models.DateField()),
                ('concepto', models.TextField()),
                ('tipo_asiento', models.CharField(choices=[('RG', 'Regular'), ('AJ', 'Ajuste')], max_length=2)),
                ('total_debe', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_haber', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ejerciciocontable')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleAsiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debe', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('haber', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.asientocontable')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.plancuentas')),
            ],
        ),
    ]
